name: jaguar_boilerplate
description: Example that shows how to use jaguar_reflect package to build Controllers using Jaguar
version: 2.4.1
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/jaguar-examples/boilerplate
environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  jaguar: ^2.4.4
  jaguar_reflect: ^2.4.0
  http: ^0.11.3

executables:
  jaguar_boilerplate_server: server
  jaguar_boilerplate_client: client
