name: boilerplate
description: Example that shows how to use jaguar_reflect package to build Apis using Jaguar.dart
version: 0.6.0
dependencies:
  jaguar: ^1.2.8
  jaguar_reflect: ^1.2.6
  http: ^0.11.3
