name: boilerplate
description: Example that shows how to use jaguar_reflect package to build Apis using Jaguar.dart
version: 0.5.0
dependencies:
  jaguar: '>0.5.3 <0.6.0'
  jaguar_reflect: '>=0.5.1 <0.6.0'
