name: boilerplate
description: Example that shows how to use jaguar_reflect package to build Apis using Jaguar.dart
version: 2.1.1
dependencies:
  jaguar: ^2.1.5
  jaguar_reflect: ^2.1.2
  http: ^0.11.3
